title: Clean Blog
email: rhsfpem41@gmail.com
description: 포트폴리오 및 개발자에 관한 정보
author: Start Bootstrap
baseurl: ""
url: "https://ionic93.github.io"

# Social Profiles
github_username: ionic93
facebook_username: rhsfpem41
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
